
# Add in main.yaml
# packages:
#   ext1:
#     url: https://github.com/wojtek-00/HomeAutomation
#     ref: relay_module
#     files:
#       - path: firmware/sprinkler_expander/sprinkler_expander.yaml
#         vars:
#           id: sprinklers_1
#           mcp_address: 32
#           refresh: 0d

substitutions:
  id: sprinkler
  mcp_address: 0x20


mcp23017:
  - id: ${id}_mcp
    address: ${mcp_address}

binary_sensor:
  - platform: gpio
    name: ${id}_in0
    pin:
      mcp23xxx: ${id}_mcp
      number: 8
      mode: INPUT
      inverted: True
    id: ${id}_in0
  - platform: gpio
    name: ${id}_in1
    pin:
      mcp23xxx: ${id}_mcp
      number: 9
      mode: INPUT
      inverted: True
    id: ${id}_in1
  - platform: gpio
    name: ${id}_in2
    pin:
      mcp23xxx: ${id}_mcp
      number: 10
      mode: INPUT
      inverted: True
    id: ${id}_in2
  - platform: gpio
    name: ${id}_in3
    pin:
      mcp23xxx: ${id}_mcp
      number: 11
      mode: INPUT
      inverted: True
    id: ${id}_in3
  - platform: gpio
    name: ${id}_in4
    pin:
      mcp23xxx: ${id}_mcp
      number: 12
      mode: INPUT
      inverted: True
    id: ${id}_in4
  - platform: gpio
    name: ${id}_in5
    pin:
      mcp23xxx: ${id}_mcp
      number: 13
      mode: INPUT
      inverted: True
    id: ${id}_in5
  - platform: gpio
    name: ${id}_in6
    pin:
      mcp23xxx: ${id}_mcp
      number: 14
      mode: INPUT
      inverted: True
    id: ${id}_in6
  - platform: gpio
    name: ${id}_in7
    pin:
      mcp23xxx: ${id}_mcp
      number: 15
      mode: INPUT
      inverted: True
    id: ${id}_in7
    
switch:
  - platform: gpio
    id: ${id}_valve_1
    name: "${id} valve 1"
    internal: true
    pin:
      mcp23xxx: ${id}_mcp
      number: 0
      mode: OUTPUT
      inverted: True

  - platform: gpio
    id: ${id}_valve_2
    name: "${id} valve 2"
    internal: true
    pin:
      mcp23xxx: ${id}_mcp
      number: 1
      mode: OUTPUT
      inverted: True

  - platform: gpio
    id: ${id}_valve_3
    name: "${id} valve 3"
    internal: true
    pin:
      mcp23xxx: ${id}_mcp
      number: 2
      mode: OUTPUT
      inverted: True

  - platform: gpio
    id: ${id}_valve_4
    name: "${id} valve 4"
    internal: true
    pin:
      mcp23xxx: ${id}_mcp
      number: 3
      mode: OUTPUT
      inverted: True

  - platform: gpio
    id: ${id}_valve_5
    name: "${id} valve 5"
    internal: true
    pin:
      mcp23xxx: ${id}_mcp
      number: 4
      mode: OUTPUT
      inverted: True

  - platform: gpio
    id: ${id}_valve_6
    name: "${id} valve 6"
    internal: true
    pin:
      mcp23xxx: ${id}_mcp
      number: 5
      mode: OUTPUT
      inverted: True

  - platform: gpio
    id: ${id}_valve_7
    name: "${id} valve 7"
    internal: true
    pin:
      mcp23xxx: ${id}_mcp
      number: 6
      mode: OUTPUT
      inverted: True

  - platform: gpio
    id: ${id}_valve_8
    name: "${id} valve 8"
    internal: true
    pin:
      mcp23xxx: ${id}_mcp
      number: 7
      mode: OUTPUT
      inverted: True


sprinkler:
  - id: ${id}_sprinkler
    main_switch: "${id}_start"
    auto_advance_switch: "${id}_auto"
    reverse_switch: "${id}_reverse"
    multiplier_number: "${id}_multiplier"
    repeat_number: "${id}_repeats"
    valve_overlap: 5s

    valves:
      - valve_switch: ${id}_zone_1
        enable_switch: ${id}_enable_zone_1
        run_duration_number:
          name: "${id}_zone_1_time"
          initial_value: 5
          unit_of_measurement: min
        valve_switch_id: ${id}_valve_1

      - valve_switch: ${id}_zone_2
        enable_switch: ${id}_enable_zone_2
        run_duration_number:
          name: "${id}_zone_2_time"
          initial_value: 5
          unit_of_measurement: min
        valve_switch_id: ${id}_valve_2

      - valve_switch: ${id}_zone_3
        enable_switch: ${id}_enable_zone_3
        run_duration_number:
          name: "${id}_zone_3_time"
          initial_value: 5
          unit_of_measurement: min
        valve_switch_id: ${id}_valve_3

      - valve_switch: ${id}_zone_4
        enable_switch: ${id}_enable_zone_4
        run_duration_number:
          name: "${id}_zone_4_time"
          initial_value: 5
          unit_of_measurement: min
        valve_switch_id: ${id}_valve_4

      - valve_switch: ${id}_zone_5
        enable_switch: ${id}_enable_zone_5
        run_duration_number:
          name: "${id}_zone_5_time"
          initial_value: 5
          unit_of_measurement: min
        valve_switch_id: ${id}_valve_5

      - valve_switch: ${id}_zone_6
        enable_switch: ${id}_enable_zone_6
        run_duration_number:
          name: "${id}_zone_6_time"
          initial_value: 5
          unit_of_measurement: min
        valve_switch_id: ${id}_valve_6

      - valve_switch: ${id}_zone_7
        enable_switch: ${id}_enable_zone_7
        run_duration_number:
          name: "${id}_zone_7_time"
          initial_value: 5
          unit_of_measurement: min
        valve_switch_id: ${id}_valve_7

      - valve_switch: ${id}_zone_8
        enable_switch: ${id}_enable_zone_8
        run_duration_number:
          name: "${id}_zone_8_time"
          initial_value: 5
          unit_of_measurement: min
        valve_switch_id: ${id}_valve_8


text_sensor:
  - platform: template
    name: "${id}_remaining_current_zone_time"
    update_interval: 1s
    lambda: |-
      auto t = id(${id}_sprinkler).time_remaining_active_valve();
      if (t.has_value()) {
        int sec = t.value();
        char buf[10];
        sprintf(buf, "%02d:%02d", sec/60, sec%60);
        return {buf};
      }
      return {"--:--"};

  - platform: template
    name: "${id}_remaining_total_time"
    update_interval: 1s
    lambda: |-
      auto t = id(${id}_sprinkler).time_remaining_current_operation();
      if (t.has_value()) {
        int sec = t.value();
        char buf[10];
        sprintf(buf, "%02d:%02d", sec/60, sec%60);
        return {buf};
      }
      return {"--:--"};
