# base.yaml

substitutions:
  sda: GPIO13
  scl: GPIO14
  led_green: GPIO9
  led_red: GPIO10
  led_blue: GPIO11

i2c:
  sda: ${sda}
  scl: ${scl}
  scan: true


sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi sygnał dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi sygnał procent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

button:
  - platform: restart
    name: "automation_node_restart"

# Konfiguracja diod LED jako output
output:
  - platform: gpio
    pin: ${led_green}
    id: output_led_green
    inverted: false  # Ustaw na true jeśli dioda świeci przy stanie LOW
    
  - platform: gpio
    pin: ${led_red}
    id: output_led_red
    inverted: false
    
  - platform: gpio
    pin: ${led_blue}
    id: output_led_blue
    inverted: false

# Zmienna do przechowywania stanu
globals:
  - id: blink_state
    type: bool
    restore_value: no
    initial_value: 'false'

# Interval co 15 sekund (1s on + 14s off)
interval:
  - interval: 10s
    then:
      - output.turn_on: output_led_blue
      - delay: 500ms
      - output.turn_off: output_led_blue

