
# Add in main.yaml
# vext1: !include
#    file: sprinkler-expander.yaml
#    vars:
#      id: ext1
#      mcp_address: 0x20

substitutions:
  id: sprinkler
  mcp_address: 0x20

mcp23017:
  - id: ${id}_mcp
    address: ${mcp_address}

binary_sensor:
  - platform: gpio
    name: ${id}_in0
    pin:
      mcp23xxx: ${id}_mcp
      number: 8
      mode: INPUT
      inverted: True
    id: ${id}_in0
  - platform: gpio
    name: ${id}_in1
    pin:
      mcp23xxx: ${id}_mcp
      number: 9
      mode: INPUT
      inverted: True
    id: ${id}_in1
  - platform: gpio
    name: ${id}_in2
    pin:
      mcp23xxx: ${id}_mcp
      number: 10
      mode: INPUT
      inverted: True
    id: ${id}_in2
  - platform: gpio
    name: ${id}_in3
    pin:
      mcp23xxx: ${id}_mcp
      number: 11
      mode: INPUT
      inverted: True
    id: ${id}_in3
  - platform: gpio
    name: ${id}_in4
    pin:
      mcp23xxx: ${id}_mcp
      number: 12
      mode: INPUT
      inverted: True
    id: ${id}_in4
  - platform: gpio
    name: ${id}_in5
    pin:
      mcp23xxx: ${id}_mcp
      number: 13
      mode: INPUT
      inverted: True
    id: ${id}_in5
  - platform: gpio
    name: ${id}_in6
    pin:
      mcp23xxx: ${id}_mcp
      number: 14
      mode: INPUT
      inverted: True
    id: ${id}_in6
  - platform: gpio
    name: ${id}_in7
    pin:
      mcp23xxx: ${id}_mcp
      number: 15
      mode: INPUT
      inverted: True
    id: ${id}_in7
  

switch:
  - platform: gpio
    name: ${id}_out0
    pin:
      mcp23xxx: ${id}_mcp
      number: 0
      mode: OUTPUT
      inverted: False
    id: ${id}_out0
  - platform: gpio
    name: ${id}_out1
    pin:
      mcp23xxx: ${id}_mcp
      number: 1
      mode: OUTPUT
      inverted: False
    id: ${id}hub1_out1
  - platform: gpio
    name: ${id}_out2
    pin:
      mcp23xxx: ${id}_mcp
      number: 2
      mode: OUTPUT
      inverted: False
    id: ${id}_out2
  - platform: gpio
    name: ${id}_out3
    pin:
      mcp23xxx: ${id}_mcp
      number: 3
      mode: OUTPUT
      inverted: False
    id: ${id}hub1_out3
  - platform: gpio
    name: ${id}_out4
    pin:
      mcp23xxx: ${id}_mcp
      number: 4
      mode: OUTPUT
      inverted: False
    id: ${id}_out4
  - platform: gpio
    name: ${id}_out5
    pin:
      mcp23xxx: ${id}_mcp
      number: 5
      mode: OUTPUT
      inverted: False
    id: ${id}_out5
  - platform: gpio
    name: ${id}_out6
    pin:
      mcp23xxx: ${id}_mcp
      number: 6
      mode: OUTPUT
      inverted: False
    id: ${id}_out6
  - platform: gpio
    name: ${id}_out7
    pin:
      mcp23xxx: ${id}_mcp
      number: 7
      mode: OUTPUT
      inverted: False
    id: ${id}_out7
