# Add in main.yaml
# packages:
#   ext1:
#     url: https://github.com/wojtek-00/HomeAutomation
#     ref: relay_module
#     files:
#       - path: firmware/relay_expander/relay_expander.yaml
#         vars:
#           device_id: relay_expander_1
#           id: expander_1
#           mcp_address: 32
#           refresh: 0d

substitutions:
  id: sprinkler
  mcp_address: 0x20
  device_id: extender_1

mcp23017:
  - id: ${id}_mcp
    address: ${mcp_address}

binary_sensor:
  - platform: gpio
    name: ${id}_in0
    device_id: ${device_id}
    pin:
      mcp23xxx: ${id}_mcp
      number: 8
      mode: INPUT
      inverted: True
    id: ${id}_in0
  - platform: gpio
    name: ${id}_in1
    device_id: ${device_id}
    pin:
      mcp23xxx: ${id}_mcp
      number: 9
      mode: INPUT
      inverted: True
    id: ${id}_in1
  - platform: gpio
    name: ${id}_in2
    device_id: ${device_id}
    pin:
      mcp23xxx: ${id}_mcp
      number: 10
      mode: INPUT
      inverted: True
    id: ${id}_in2
  - platform: gpio
    name: ${id}_in3
    device_id: ${device_id}
    pin:
      mcp23xxx: ${id}_mcp
      number: 11
      mode: INPUT
      inverted: True
    id: ${id}_in3
  - platform: gpio
    name: ${id}_in4
    device_id: ${device_id}
    pin:
      mcp23xxx: ${id}_mcp
      number: 12
      mode: INPUT
      inverted: True
    id: ${id}_in4
  - platform: gpio
    name: ${id}_in5
    device_id: ${device_id}
    pin:
      mcp23xxx: ${id}_mcp
      number: 13
      mode: INPUT
      inverted: True
    id: ${id}_in5
  - platform: gpio
    name: ${id}_in6
    device_id: ${device_id}
    pin:
      mcp23xxx: ${id}_mcp
      number: 14
      mode: INPUT
      inverted: True
    id: ${id}_in6
  - platform: gpio
    name: ${id}_in7
    device_id: ${device_id}
    pin:
      mcp23xxx: ${id}_mcp
      number: 15
      mode: INPUT
      inverted: True
    id: ${id}_in7
  

switch:
  - platform: gpio
    name: ${id}_out0
    device_id: ${device_id}
    pin:
      mcp23xxx: ${id}_mcp
      number: 0
      mode: OUTPUT
      inverted: False
    id: ${id}_out0
  - platform: gpio
    name: ${id}_out1
    device_id: ${device_id}
    pin:
      mcp23xxx: ${id}_mcp
      number: 1
      mode: OUTPUT
      inverted: False
    id: ${id}hub1_out1
  - platform: gpio
    name: ${id}_out2
    device_id: ${device_id}
    pin:
      mcp23xxx: ${id}_mcp
      number: 2
      mode: OUTPUT
      inverted: False
    id: ${id}_out2
  - platform: gpio
    name: ${id}_out3
    device_id: ${device_id}
    pin:
      mcp23xxx: ${id}_mcp
      number: 3
      mode: OUTPUT
      inverted: False
    id: ${id}hub1_out3
  - platform: gpio
    name: ${id}_out4
    device_id: ${device_id}
    pin:
      mcp23xxx: ${id}_mcp
      number: 4
      mode: OUTPUT
      inverted: False
    id: ${id}_out4
  - platform: gpio
    name: ${id}_out5
    device_id: ${device_id}
    pin:
      mcp23xxx: ${id}_mcp
      number: 5
      mode: OUTPUT
      inverted: False
    id: ${id}_out5
  - platform: gpio
    name: ${id}_out6
    device_id: ${device_id}
    pin:
      mcp23xxx: ${id}_mcp
      number: 6
      mode: OUTPUT
      inverted: False
    id: ${id}_out6
  - platform: gpio
    name: ${id}_out7
    device_id: ${device_id}
    pin:
      mcp23xxx: ${id}_mcp
      number: 7
      mode: OUTPUT
      inverted: False
    id: ${id}_out7
